### ISSUE TITLE
`ipsec`: command not found

### ISSUE THREAD

**Issue by morpheusthewhite** [morpheusthewhite/nordpy#56]
Nordpy fails when `ipsec` command is missing.

**Logs**

```
Traceback (most recent call last):
  File "/usr/local/bin/nordpy", line 62, in <module>
    main()
  File "/usr/local/bin/nordpy", line 56, in main
    from bin.gui import gui
  File "/usr/share/NordPy/bin/gui.py", line 10, in <module>
    from bin.vpn_util.vpn import *
  File "/usr/share/NordPy/bin/vpn_util/vpn.py", line 5, in <module>
    IPSEC_EXISTS = ipsec_exists()
  File "/usr/share/NordPy/bin/vpn_util/ikev2.py", line 52, in ipsec_exists
    (_, err) = Popen(["ipsec", "--version"], stdout=PIPE, stderr=PIPE, universal_newlines=True).communicate()
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ipsec'
Retrieved stats
Retrieved stats
```

**Comment by morpheusthewhite** [comment]
@dreieck-aur could you please provide the following information:
 - Linux Distribution
 - NordPy version (`git log --pretty=format:'%H' -n 1`)

**Comment by mmmmmmbeer** [comment]
I had the exact same error when running v1.3.5 on Fedora 36. I fixed it by installing libreswan-4.7-1.fc36.x86_64 via dnf.
